### ISSUE TITLE
Изменить принцип атаки ворона улучшить траекторию полета и увеличить коллайдер ворона

### ISSUE THREAD

**Issue by Hzpriezz** [successeven/WayOfLastSoul#9]

**Comment by Hzpriezz** [comment]
Короче надо чтобы он пикировал быстро в конце непного по прямой затем при атаке подвисал на какое то время в той точке и медленно упархнул, еще можно добавить - если он не попал по игроку то взлет сделать быстрее (ну это уже изврат при желании)

**Comment by successeven** [comment]
Сама троектория это уже изврат. делать не буду сейчас. пока траетория останется текущей
